four_pixels_default:
    resource: "@FourPixelsBundle/Controller/DefaultController.php"
    type:     rest
four_pixels_slack:
    resource: "@FourPixelsBundle/Controller/SlackController.php"
    type:     rest
four_pixels_talkabit:
    resource: "@FourPixelsBundle/Controller/TalkabitController.php"
    type:     rest
